all:
  vars:
    public_network: 192.168.99.0/24
    admin_secret: 'AQBYJ15gAAAAABAADq5k30KhQ63IyUW9ce/s1A=='
    mgr_secret: 'AQBYJ15gAAAAABAADq5k30KhQ63IyUW9ce/s1A=='
    copy_admin_key: true
    containerized_deployment: false
    fetch_directory: fetch/
    ansible_ssh_user: ceph-admin
    ansible_become: true
    ansible_become_method: sudo
#   ansible_become_user: root
    ansible_python_interpreter: /usr/bin/python3
    ceph_origin: distro
    ceph_use_distro_backports: true
#   ceph_repository: community
#   ceph_mirror: http://httpredir.debian.org
#   ceph_stable_release: nautilus
#   ceph_stable_distro_source: buster-backports
#   ceph_stable_repo: "{{ ceph_mirror }}/debian "
    ip-version: ipv4
    ceph_tcmalloc_max_total_thread_cache: 134217728
    dashboard_enabled: false
#   ceph_conf_overrides:
#     global:
#       mon host: 192.168.99.41
  children:
    mons:
      hosts:
        mon1.local:
          monitor_address: 192.168.99.41
        rgw1.local:
          monitor_address: 192.168.99.42
        rgw2.local:
          monitor_address: 192.168.99.43
    mgrs:
      hosts:
        mon1.local:
        rgw1.local:
        rgw2.local:
    osds:
      vars:
        osd_auto_discovery: true
      hosts:
        osd1.local:
        osd2.local:
        osd3.local:
    rgws:
      vars:
        copy_admin_key: false
        rgw_create_pools:
          "{{ rgw_zone }}.rgw.buckets.data":
            pg_num: 64
            size: 3
            type: replicated
          "{{ rgw_zone }}.rgw.buckets.index":
            pg_num: 16
            size: 3
            type: replicated
          "{{ rgw_zone }}.rgw.meta":
            pg_num: 8
            size: 3
            type: replicated
          "{{ rgw_zone }}.rgw.log":
            pg_num: 8
            size: 3
            type: replicated
          "{{ rgw_zone }}.rgw.control":
            pg_num: 8
            size: 3
            type: replicated
      hosts:
        rgw1.local:
          radosgw_address: 192.168.99.42
        rgw2.local:
          radosgw_address: 192.168.99.43
    rgwloadbalancers:
      vars:
        virtual_ip_interface: ens6
        virtual_ip_netmask: 24
        virtual_ips:
          - 192.168.99.250
          - 192.168.99.251
        haproxy_frontend_ssl_certificate:
          /etc/ssl/certs/ceph-rgw-combined.crt
      hosts:
        rgw1.local:
        rgw2.local:
